In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
import sklearn.metrics


In [2]:
# laod data set
tree = pd.read_csv('F:\\machine learning\\datasets\\COURSERA\\t.csv')
tree.head(5)

BIO_SEX  HISPANIC  WHITE  BLACK  NAMERICAN  ASIAN        age  TREG1  \
0      2.0       0.0    0.0    1.0        0.0    0.0        NaN    0.0   
1      2.0       0.0    0.0    1.0        0.0    0.0  19.427397    1.0   
2      1.0       0.0    1.0    0.0        0.0    0.0        NaN    0.0   
3      1.0       0.0    0.0    1.0        0.0    0.0  20.430137    1.0   
4      2.0       0.0    0.0    1.0        0.0    0.0        NaN    0.0   

   ALCEVR1  ALCPROBS1   ...     ESTEEM1  VIOL1  PASSIST  DEVIANT1  SCHCONN1  \
0      1.0          2   ...        47.0    4.0        0       5.0       NaN   
1      1.0          1   ...        35.0    1.0        0       5.0      22.0   
2      0.0          0   ...        45.0    0.0        0       1.0      30.0   
3      0.0          0   ...        47.0    4.0        1       4.0      19.0   
4      1.0          0   ...        39.0    0.0        0       5.0      32.0   

       GPA1  EXPEL1  FAMCONCT  PARACTV  PARPRES  
0       NaN     0.0      24.3      8.0     15.0  
1  2.333333     0.0      23.3      9.0     15.0  
2  2.250000     0.0      24.3      3.0     15.0  
3  2.000000     0.0      18.7      6.0     14.0  
4  3.000000     0.0      20.0      9.0      6.0  

[5 rows x 25 columns]

In [3]:
# drop na values & check the information of each column
print(tree.shape)
tree.dropna(inplace = True)
print(tree.shape)
print(tree.describe())

(6504, 25)
(4575, 25)
           BIO_SEX     HISPANIC        WHITE        BLACK    NAMERICAN  \
count  4575.000000  4575.000000  4575.000000  4575.000000  4575.000000   
mean      1.521093     0.111038     0.683279     0.236066     0.036284   
std       0.499609     0.314214     0.465249     0.424709     0.187017   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000     0.000000     0.000000     0.000000     0.000000   
50%       2.000000     0.000000     1.000000     0.000000     0.000000   
75%       2.000000     0.000000     1.000000     0.000000     0.000000   
max       2.000000     1.000000     1.000000     1.000000     1.000000   

             ASIAN          age        TREG1      ALCEVR1    ALCPROBS1  \
count  4575.000000  4575.000000  4575.000000  4575.000000  4575.000000   
mean      0.040437    16.493052     0.176393     0.527432     0.369180   
std       0.197004     1.552174     0.381196     0.499302     0.894947   
min       0.000

In [4]:
# modeling and prediction
# estimating the correlation between different attributes and dependent variable
def calculate_corr(cell):
    return tree['TREG1'].corr(cell)
crel = tree.apply(calculate_corr)
crel = crel.abs().sort_values(ascending = False).drop('TREG1')
crel.head(5)

marever1     0.433483
DEVIANT1     0.336319
ALCEVR1      0.318596
ALCPROBS1    0.296120
GPA1         0.236667
dtype: float64

In [5]:
# use top 5, top 7 & top 3 attributes for construction of decision tree
# convert crel into respective list
top_5_attr = list(crel.index[:5])
predicters = tree[top_5_attr]
targets = tree['TREG1']
pred_train, pred_test, target_train, target_test = train_test_split(predicters, targets, test_size = 0.4 )
print (pred_train.shape)
print (pred_test.shape)
print (target_train.shape)
print (target_test.shape)

(2745, 5)
(1830, 5)
(2745,)
(1830,)


In [6]:
# fit model in decision tree
classifier = DecisionTreeClassifier()
classifier  = classifier.fit(pred_train, target_train)
# check the training error
print (sklearn.metrics.accuracy_score(target_train, classifier.predict(pred_train)))
# prediction for test set
predictions = classifier.predict(pred_test)
print (sklearn.metrics.accuracy_score(target_test, predictions))
sklearn.metrics.confusion_matrix(target_test, predictions)

0.930418943534
0.803278688525


array([[1369,  123],
       [ 237,  101]])

In [7]:
# fit model using top 7 correlated attributes
top_7_attr = list(crel.index[:7])
predicters = tree[top_7_attr]
targets = tree['TREG1']
pred_train, pred_test, target_train, target_test = train_test_split(predicters, targets, test_size = 0.4 )
# fit model in decision tree
classifier = DecisionTreeClassifier()
classifier  = classifier.fit(pred_train, target_train)
# check the training error
print (sklearn.metrics.accuracy_score(target_train, classifier.predict(pred_train)))
# prediction for test set
predictions = classifier.predict(pred_test)
print (sklearn.metrics.accuracy_score(target_test, predictions))
sklearn.metrics.confusion_matrix(target_test, predictions)

0.986520947177
0.786885245902


array([[1298,  197],
       [ 193,  142]])

In [8]:
#fit model using top 3 correlated attributes
top_3_attr = list(crel.index[:3])
predicters = tree[top_3_attr]
targets = tree['TREG1']
pred_train, pred_test, target_train, target_test = train_test_split(predicters, targets, test_size = 0.4 )
# fit model in decision tree
classifier = DecisionTreeClassifier()
classifier  = classifier.fit(pred_train, target_train)
# check the training error
print (sklearn.metrics.accuracy_score(target_train, classifier.predict(pred_train)))
# prediction for test set
predictions = classifier.predict(pred_test)
print (sklearn.metrics.accuracy_score(target_test, predictions))
sklearn.metrics.confusion_matrix(target_test, predictions)

0.84262295082
0.824043715847


array([[1444,   43],
       [ 279,   64]])

In [9]:
#Displaying the decision tree
from sklearn import tree
#from StringIO import StringIO
from io import StringIO
#from StringIO import StringIO 
from IPython.display import Image
out = StringIO()
tree.export_graphviz(classifier, out_file=out)
import pydotplus
graph=pydotplus.graph_from_dot_data(out.getvalue())
Image(graph.create_png())

InvocationException: GraphViz's executables not found